version: '3.8'

services:
  web:
    build: .
    container_name: sistema_login
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      # Persist SQLite database
      - ./instance:/app/instance
      # Persist User uploads
      - ./static/uploads:/app/static/uploads
      # Persistencia de los horarios PDF generados
      - ./horarios:/app/horarios
      # Persist logs
      - ./logs:/app/logs
      # Persist backups
      - ./backups:/app/backups
    env_file:
      - path: .env
        required: false
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
